sudo: false  # Use container-based infrastructure
language: python
cache: pip
python:
  - "2.7"
  - "3.4"
before_install:
  # Commands below copied from: http://conda.pydata.org/docs/travis.html
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  # reset the shell's lookup table for program name to path mappings
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
addons:
  apt:
    packages:
    # install pandoc for use with pypandoc for converting the README
    # from markdown to RST
    - pandoc
install:
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy nose pandas matplotlib
  - source activate test-environment
  - pip install pypandoc statsmodels
  - pip install -r requirements.txt
  - pip install .
  - pip install coveralls
script:
  - ./lint.sh
  - nosetests -w test -sv --with-coverage --cover-package=survivalstan
after_success:
  coveralls
deploy:
 provider: pypi
 user: hammerlab
 password: # See http://docs.travis-ci.com/user/encryption-keys/
  secure: "weztV3HeMuiBShFxRrFS8IMWh/Yu+wjN8IrCT4IyB3I1GU5n3HIqKji0+M1/VWTEGhwVqPZw9yY0zQle9MYZRp4/QLQh8qLOEs3GvM4xWe3wEzJIm0nAWbyYd1dK1O3dzdyXRFenlw9NDFzgYQDrxnM/z9f4C/v2KanWkLJxoOhejyRnuyQnNlzUSAUyP0AS3TkhD3BwK0NVeW3oynrdsKjsQpfJDk1lqRzhUEXe+m6/g6qN1uFFYvLYtpxFGxNubxzduMDPa2RR9GZtlMkwQIgEsY6DBem/85Uhel2tjm59MJjxp5K3cGtF/IzQIUBEe0WlK2LpbKlLGkZZ7thMGO2XeivrPYrmuD3isUmYFDTwvjp4MnbOS4m44ZrNZzTgwP7Icz7t6M4+NWdSNv274K0lh3Ag2mIvUVA8NYhFWCj31fWqEPd8kk/ADta/+Pi6vWDTFK2dZllw2tZtnnkFVmfkm+PteGyHUGmh0lO9zAtzjd05YycFM3ipjNFQChBMwZN75MXptnBDM8Tg8LuckxNfZ7wmBALJ3JndZqKbHZqi67vGZ2KabmODozHdyZLh7o6YRLuXx5M8u6TUBEadpFHuA8KmQHl2rnFJmVDbg7hPoDiJ4yLKB1EgrWIEDAhokHkXY44LZL40qbZ+X/28D3YGOSr4NRRUdLXTuK2fPCQ="
 on:
   branch: master
   tags: True
